# Makefile for utf-256 (Go version)

APP_NAME = utf-256
SRC_FILE = ${APP_NAME}.go

.PHONY: all clean build

all: build

build:
	go build $(SRC_FILE)

run:
	go run ${SRC_FILE}

clean:
	rm -f ${APP_NAME}
